#!/bin/bash

# Get the current working directory
current_dir=$(pwd)

# Get the parent of the working directory
parent_dir=$(dirname "$current_dir")

# Loop through all the HTML files in the current working directory
for file in "$current_dir"/*.html
do
  # Check if the file exists in the parent of the working directory
  if [ "$file" -nt "$parent_dir/${file##*/}" ]
  then
    # Copy the file to the parent of the working directory
    cp "$file" "$parent_dir"
  fi
done
